apiVersion: v2
appVersion: "3.0"
description: A Helm chart for kong/kong
name: kong
version: 2.13.1
dependencies:
  - name: kong
    version: 2.13.1
    repository: https://charts.konghq.com
    alias: kong